Add support for U55N
Xilinx/xup_vitis_network_example pull request #111
Opened 2023-08-23 10:02 UTC by HongshiTan

* refactor ping_fpga example for a better config of ip address.
* add dump of arp table in ping_fpga example

2023-08-23 12:47 UTC, mariodruiz requested changes
Hi @HongshiTan,

Thank you for your contribution, please address my comments

2023-08-23 12:47 UTC, mariodruiz commented on Ethernet/platform.tcl
> +} elseif {[string first "vck5000" ${board}] != -1} {
There's no current plan to support VCK5000, please remove this

2023-08-23 12:47 UTC, mariodruiz commented on xrt_host_api/examples/ping_fpga/ping_fpga.cpp
> +    for (uint32_t  i = 0; i < ARRAY_SIZE(ip_lut); i++)
To keep consistency put the curly brace `{` at the same level of the for

2023-08-23 12:47 UTC, mariodruiz commented on xrt_host_api/examples/ping_fpga/ping_fpga.cpp
> +        if(std::string(ip_lut[i].hostname) ==  hostname)
ditto

2023-08-23 12:47 UTC, mariodruiz commented on xrt_host_api/examples/ping_fpga/ping_fpga.cpp
> +            {
ditto

2023-08-23 12:47 UTC, mariodruiz commented on xrt_host_api/examples/ping_fpga/ping_fpga.cpp
> +    {
ditto

2023-08-23 12:47 UTC, mariodruiz commented on xrt_host_api/examples/ping_fpga/ping_fpga.cpp
> +    {
ditto

2023-08-23 12:47 UTC, mariodruiz commented on xrt_host_api/examples/ping_fpga/ping_fpga.cpp
> +    std::cout <<"Dump arp table" << std::endl;
What is the value of dumping the ARP table by default? This could be a paramenter

2023-08-23 17:25 UTC, HongshiTan commented on Ethernet/platform.tcl
> +} elseif {[string first "vck5000" ${board}] != -1} {
OK. I'm doing the test on VCK5000 now, will push it when finished.

2023-08-23 17:25 UTC, HongshiTan commented
Have resolved all your comments

2023-08-24 07:39 UTC, mariodruiz approved these changes

2023-08-24 07:40 UTC, merged