add HostC++
Xilinx/xup_vitis_network_example pull request #52
Opened 2022-04-05 11:43 UTC by fpgafais

- minimalistic C++ wrapper over XRT native API with example UDP receiver and transceiver applications
- tested on U280 with basic kernels instances

 Signed-off-by: Grzegorz Korcyl <grzegorz.korcyl@uj.edu.pl>

2022-04-05 12:14 UTC, mariodruiz commented
Hi @fpgafais,

Thank you for submitting this PR.
A few minor comments for now,
- can you change the directory name to `host_xrt`?
- Add license header a two-line license like below

```C
# Copyright (C) <your Copyright>
#
# SPDX-License-Identifier: BSD-3-Clause
```

2022-04-05 12:23 UTC, mariodruiz requested changes

2022-04-05 12:23 UTC, mariodruiz commented on HostC++/README.md
> +The project allows to access HW kernel and IPs included in XUP VNx (http://github.com/Xilinx/xup_vitis_network_example) from any C++ application.
~included in XUP VNx (http://github.com/Xilinx/xup_vitis_network_example)~

included in this repository.

2022-04-05 12:23 UTC, mariodruiz commented on HostC++/README.md
> +* Make sure the XRT environment setting are set and XRT is installed in /opt/Xilinx/xrt
/opt/xilinx/xrt (lowercase)

2022-04-05 12:23 UTC, mariodruiz commented on HostC++/README.md
> +* run cmake ../ and cmake --build .
Add actual commands in a code snippet box, for instance

```bash
mkdir build; cd build
cmake ..
cmake --build .
```

2022-04-05 12:23 UTC, mariodruiz commented on HostC++/README.md
> +grzegorz.korcyl@uj.edu.pl
Please rename this section to **Support**.

I would also include, this driver has been contributed by ... for support create and issue and assign \<your user id\>

Your email may be optional if you provide your github id

2022-04-05 16:56 UTC, mariodruiz commented on host_xrt/exec/alveo_rx.cpp
> +    l1.setMyAddresses("192.168.0.2", "ab:cd:ef:02:02", 10001);
As wish list you could get the MAC address from the platform member of the namespace `info` https://xilinx.github.io/XRT/master/html/xrt_native.main.html#_CPPv4N3xrt4info8platformE

I was playing with this using `pyxrt` the Python bindings of the native XRT driver. https://github.com/mariodruiz/PYNQ/blob/image_v2.8.pyxrt/pynq/pl_server/xrt_device.py#L378-L385

2022-04-05 16:56 UTC, mariodruiz commented on host_xrt/exec/alveo_rx.cpp
> +    std::cout << "Bitfile loaded " << uuid << std::endl;
I would be good to get the xclbin as argument as well as device id, there could be multiple devices in the server

2022-04-05 16:56 UTC, mariodruiz commented on host_xrt/include/alveo_vnx_configs.h
> +#define ALVEO_DEVICE "xilinx_u280_xdma_201920_3"
This could be the default value in cmake, but perhaps it can also be an argument to cmake so it is easy to target a different boards

2022-04-05 16:56 UTC, mariodruiz commented on host_xrt/src/fpga_ip.cpp
> +        return 1;
You could return `EINVAL`

2022-04-05 16:56 UTC, mariodruiz commented on host_xrt/src/fpga_ip.cpp
> +        return 1;
You could return `EINVAL`

2022-04-11 09:41 UTC, fpgafais commented on host_xrt/exec/alveo_rx.cpp
> +    l1.setMyAddresses("192.168.0.2", "ab:cd:ef:02:02", 10001);
platform is not yet available in info in xrt 2.11 which is the default in packages to download for Alveo; problems compiling xrt 2.14; will be fixed in the future

2022-04-13 18:51 UTC, fpgafais commented
Sure, please go on. The current state is sufficient for our applications but please let us know if you find elements to change or improve

2022-04-13 19:18 UTC, merged