Low level xrt api
Xilinx/xup_vitis_network_example pull request #79
Opened 2022-07-27 14:39 UTC by TristanLaan

2022-07-28 17:20 UTC, mariodruiz commented on xrt_host_api/include/vnx/networklayer.hpp
> +constexpr std::size_t eth_out_bytes = 0x10b0;
Is there an automatic way to get the offset instead of hard coded?

2022-07-28 17:24 UTC, mariodruiz requested changes

2022-07-28 17:24 UTC, mariodruiz commented on xrt_host_api/examples/ping_fpga/README.md
> +This example program loads the VNx xclbin unto the FPGA, tests the link on the
unto -> onto

2022-07-28 17:24 UTC, mariodruiz commented on xrt_host_api/examples/ping_fpga/README.md
> +`ping_fpga.cpp` contains the correct path to the xclbins, the correct hostnames,
it would be good if the xclbin can be passed as argument

2022-07-29 09:34 UTC, TristanLaan commented on xrt_host_api/include/vnx/networklayer.hpp
> +constexpr std::size_t eth_out_bytes = 0x10b0;
Unfortunately not with the XRT native API no… We could create a separate Python script that extracts the information from the XCLBIN file and stores the config to a JSON file that can be accessed by the program at runtime.

2022-07-29 09:55 UTC, mariodruiz commented on xrt_host_api/include/vnx/cmac.hpp
> +
It would be good to have a function to read the statistics.

2022-07-29 09:56 UTC, mariodruiz commented
PR looks good. A bit more comments on the code would be good

2022-07-29 10:31 UTC, mariodruiz commented on xrt_host_api/include/vnx/cmac.hpp
> +
I could be empty for now

2022-07-29 10:44 UTC, TristanLaan commented on xrt_host_api/include/vnx/cmac.hpp
> +
Yes, I'm adding some comments + a skeleton for this function.

2022-07-29 13:27 UTC, mariodruiz approved these changes

2022-07-29 13:29 UTC, mariodruiz commented
@fpgafais would you help me review this? 

My colleagues need a lower level driver for ACCL, so they are proposing this PR. I think your code can build on top of this.

2022-08-15 13:23 UTC, mariodruiz requested changes

2022-08-15 13:23 UTC, mariodruiz commented on xrt_host_api/examples/ping_fpga/ping_fpga.cpp
> +  xrt::device device = xrt::device(0);
Can you please also pass the device as argument? if this is not specified, default to device 0

2022-08-15 13:23 UTC, mariodruiz commented on xrt_host_api/examples/ping_fpga/CMakeLists.txt
> +#   Copyright (c) 2020-2022, Xilinx, Inc.
Can you please go with two-line header?

```C
// Copyright (C) 2022 Xilinx, Inc
// SPDX-License-Identifier: BSD-3-Clause
```

2022-09-13 11:00 UTC, TristanLaan commented on xrt_host_api/examples/ping_fpga/ping_fpga.cpp
> +  xrt::device device = xrt::device(0);
I've changed this to an environment variable.

2022-09-13 11:14 UTC, mariodruiz commented on xrt_host_api/examples/ping_fpga/ping_fpga.cpp
> +  xrt::device device = xrt::device(0);
I think this is not good enough. What if there are multiple devices in the system? 

This should be an argument passed to executable. Of course it should be set to 0 by default

2022-09-13 12:58 UTC, TristanLaan commented on xrt_host_api/examples/ping_fpga/ping_fpga.cpp
> +  xrt::device device = xrt::device(0);
Have you looked at the latest commit? This is no longer up to date. You can change the device by setting XRT_DEVICE=1.

2022-09-13 13:10 UTC, mariodruiz commented on xrt_host_api/examples/ping_fpga/ping_fpga.cpp
> +  xrt::device device = xrt::device(0);
Yes, I looked at the latest commit. Hence my comment. I do not think using env variables is a good way to specify the device id. It should be passed as argument

2022-09-14 08:31 UTC, TristanLaan commented on xrt_host_api/examples/ping_fpga/ping_fpga.cpp
> +  xrt::device device = xrt::device(0);
I've now removed the feature to pass multiple xclbin files and made the device index an optional argument to the program.

2022-09-15 06:53 UTC, mariodruiz approved these changes
Looks good. Can you please sing-off the PR?

2022-09-15 06:54 UTC, mariodruiz commented
I'll make time next week to test this and merge.

2022-09-23 12:06 UTC, mariodruiz approved these changes

2022-09-23 12:06 UTC, merged